call plug#begin('~/.vim/plugged')

" python-mode
Plug 'klen/python-mode'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" Using git URL
" Plug 'junegunn/vim-github-dashboard.git'

" Go
Plug 'fatih/vim-go'

Plug 'airblade/vim-gitgutter'

Plug 'altercation/vim-colors-solarized'

" Powerline
Plug 'powerline/powerline'

" CtrlP
Plug 'kien/ctrlp.vim'

Plug 'Xuyuanp/nerdtree-git-plugin'

Plug 'tpope/vim-fugitive'

" Unmanaged plugin (manually installed and updated)
" Plug '~/my-prototype-plugin'

" Add plugins to &runtimepath
call plug#end()

syntax on
filetype on
filetype plugin indent on
set tabstop=4 expandtab shiftwidth=4 softtabstop=4
set foldmethod=indent foldlevel=99 "python-compatible folding
set number "line numbers
set relativenumber "relative numbers too
set clipboard=unnamed
set hlsearch
set incsearch
set ignorecase
set smartcase
colorscheme solarized
set background=dark
" tmp file handling
set nobackup
set nowritebackup
set noswapfile
let mapleader = "\<Space>"
set laststatus=2
set diffopt+=vertical

" GitGutter
nmap <Leader>ha <Plug>GitGutterStageHunk
nmap <Leader>hu <Plug>GitGutterRevertHunk
highlight GitGutterChange ctermfg=3 guifg=#bbbb00
highlight GitGutterAdd ctermfg=2 guifg=#009900
highlight GitGutterDelete ctermfg=1 guifg=#ff2222
highlight GitGutterChangeDelete ctermfg=3 guifg=#bbbb00
highlight clear SignColumn
highlight SignColumn ctermfg=12 guifg=Cyan

nmap <C-n> :set nonumber!<CR>:GitGutterToggle<CR>
nmap <F8> :TagbarToggle<CR>

" indent shortcut
vnoremap < <gv
vnoremap > >gv

" rope conf
let g:pymode_rope_goto_definition_bind = "<Leader>g"

set rtp+=~/.vim/plugged/powerline/powerline/bindings/vim

" disable arrow keys
" noremap <Up> <NOP>
" noremap <Down> <NOP>
" noremap <Left> <NOP>
" noremap <Right> <NOP>

" NerdTREE (close if last window open)
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" Bind NerdTREE
nmap <C-m> :NERDTreeToggle<CR>
